### ISSUE TITLE
How Parsers are generated for dotnet-netrace project?

### ISSUE THREAD

**Issue by PurnaChandraPanda** [lowleveldesign/dotnet-netrace#1]
I am writing a small project that involves ETW events parsing for both .NET Core and .NET Full events. I saw the reference for TraceParserGen. However, I could not understand how custom parsers for provider such as **Microsoft-System-Net-HttpListener** is generated. Could you please help here?

**Comment by lowleveldesign** [comment]
I am sorry for the delay with my response - I somehow missed this issue 🙁 AFAIR, I generated the manifests for TraceParserGen using [PerfView's DumpEventSourceManifests](https://github.com/microsoft/perfview/blob/master/documentation/TraceEvent/TraceEventProgrammersGuide.md#getting-the-xml-manifest) command.
